run:
 # default concurrency is a available CPU number
 concurrency: 4

 # timeout for analysis, e.g. 30s, 5m, default is 1m
 deadline: 2m

linters:
 disable:
   - gochecknoglobals  # TODO: remove
   - dupl
   - lll
   - funlen  # TODO: remove
   - gomnd
   - goerr113  # TODO: remove would be good to have modern error handling
   - testpackage  # I want to test internal methods
 presets:
   - bugs
   - unused
   - complexity
   - style

issues:
  exclude-rules:
    # Exclude gosec on test files
    - path: internal/test/
      text: "G404"
      linters:
        - gosec
