run:
 # default concurrency is a available CPU number
 concurrency: 4

 # timeout for analysis, e.g. 30s, 5m, default is 1m
 deadline: 2m

linters:
 disable:
   - gochecknoglobals  # TODO: remove
   - dupl
   - lll
   - funlen  # TODO: remove
   - gomnd
 presets:
   - bugs
   - unused
   - complexity
   - style
