name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.adoc'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.adoc'
      - '.gitignore'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
            sh -s -- -b "$(go env GOPATH)/bin" v1.23.1

      - name: Run golangci-lint
        run: |
          "$(go env GOPATH)/bin/golangci-lint" run

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: ./build.sh ${{ github.sha }} ${{ github.ref }} ${{ github.actor }}

