name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.adoc'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.adoc'
      - 'LICENSE'
      - '.gitignore'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run the linters
        run: make lint
      - name: Check if go.mod is up to date
        run: make check-tidy

  test:
    strategy:
      matrix:
        go-version:
          - 1.13.x
        os:
        - macos-latest
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
          pulley_build_username: ${{ github.actor }}
          pulley_git_sha: ${{ github.sha }}
        run: make build
